// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4537.Steam2017V21.subsystems;

import org.usfirst.frc4537.Steam2017V21.Config;
import org.usfirst.frc4537.Steam2017V21.RobotMap;
import org.usfirst.frc4537.Steam2017V21.commands.*;
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Climber extends Subsystem {
    private final static DigitalInput limitSwitch = RobotMap.climberLimitSwitch;
    private final static CANTalon climbMotor1 = RobotMap.climbMotor1;
    private final static CANTalon climbMotor2 = RobotMap.climbMotor2;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
    	setDefaultCommand(new climbStop());
    }
    
    public static void climbUp() {
    	climbMotor1.set(-Config.CLIMBER_SPEED);
    	climbMotor2.set(-Config.CLIMBER_SPEED);
    }
    
    public static void climbDown() {
    	climbMotor1.set(Config.CLIMBER_SPEED/4);
    	climbMotor2.set(Config.CLIMBER_SPEED/4);
    }
    
    public static void climbStop() {
    	climbMotor1.set(0);
    	climbMotor2.set(0);
    }
    
    public static boolean climbRead() {
    	return limitSwitch.get();
    }
}

